"""BridgeMetrics: Real-Time Delivery Analytics and Governance Dashboard.

BridgeMetrics provides real-time visibility into the AI-to-production pipeline,
tracking key performance indicators that matter: Mean Merge Time (MMT),
Escaped Defect Rate (EDR), Cost per Solved Ticket (CpST), and AI Code Quality
Index. It replaces vanity metrics (lines of code, token cost) with
outcome-based metrics that measure actual delivery effectiveness.

Key Metrics Tracked:
- Mean Merge Time (MMT): Time from PR open to merge
- Escaped Defect Rate (EDR): Bugs found in production per release
- Code Review Burden: Hours spent reviewing AI-generated code
- AI Code Ratio: Percentage of code generated by AI
- Security Vulnerability Density: Vulnerabilities per 1000 lines
- Pipeline Throughput: PRs merged per week
- Cost per Solved Ticket (CpST): Total cost / resolved tickets
"""

import json
import os
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path
from typing import Optional


class MetricType(Enum):
    COUNTER = "counter"
    GAUGE = "gauge"
    HISTOGRAM = "histogram"
    DURATION = "duration"


@dataclass
class MetricPoint:
    name: str
    value: float
    timestamp: float
    labels: dict = field(default_factory=dict)
    metric_type: MetricType = MetricType.GAUGE


@dataclass
class PipelineMetrics:
    """Snapshot of key pipeline metrics."""
    # Time metrics (hours)
    mean_merge_time: float = 0.0
    median_merge_time: float = 0.0
    p95_merge_time: float = 0.0

    # Quality metrics
    escaped_defect_rate: float = 0.0       # per release
    ai_code_ratio: float = 0.0              # 0.0-1.0
    vulnerability_density: float = 0.0     # per 1000 LOC
    review_burden_hours: float = 0.0       # per week

    # Throughput metrics
    prs_merged: int = 0
    prs_rejected: int = 0
    total_lines_changed: int = 0
    ai_generated_lines: int = 0

    # Cost metrics
    cost_per_solved_ticket: float = 0.0
    estimated_token_cost: float = 0.0

    # Team metrics
    avg_review_time_hours: float = 0.0
    review_backlog: int = 0
    active_contributors: int = 0

    # Trend indicators
    trend_direction: str = "stable"
    week_over_week_change: float = 0.0


@dataclass
class TrendReport:
    metric_name: str
    current_value: float
    previous_value: float
    change_pct: float
    trend: str          # "improving", "declining", "stable"
    alert: bool


class BridgeMetrics:
    """Real-time delivery analytics and governance.

    Usage:
        metrics = BridgeMetrics()
        metrics.record_pr_merge(merge_time_hours=4.5, ai_code_ratio=0.6)
        metrics.record_defect_escape(severity="high")
        snapshot = metrics.get_pipeline_snapshot()
        print(f"MMT: {snapshot.mean_merge_time}h, EDR: {snapshot.escaped_defect_rate}")
    """

    def __init__(self, storage_path: Optional[str] = None):
        self.storage_path = storage_path or ".codebridge_cache/metrics.json"
        self._pr_merge_times: list[float] = []
        self._defect_escapes: list[dict] = []
        self._reviews: list[dict] = []
        self._tickets: list[dict] = []
        self._pr_count = 0
        self._ai_lines = 0
        self._total_lines = 0
        self._vulnerabilities = 0
        self._total_loc = 0
        self._snapshots: list[tuple[float, PipelineMetrics]] = []
        self._load_state()

    def record_pr_merge(self, merge_time_hours: float, ai_code_ratio: float = 0.0,
                        lines_changed: int = 0, ai_lines: int = 0, reviewer_count: int = 1,
                        review_time_hours: float = 0.0):
        """Record a PR merge event."""
        self._pr_merge_times.append(merge_time_hours)
        self._pr_count += 1
        self._ai_lines += ai_lines
        self._total_lines += lines_changed

        self._reviews.append({
            "timestamp": time.time(),
            "merge_time": merge_time_hours,
            "ai_ratio": ai_code_ratio,
            "lines": lines_changed,
            "reviewer_count": reviewer_count,
            "review_time": review_time_hours,
        })

        if len(self._pr_merge_times) % 10 == 0:
            self._save_state()

    def record_defect_escape(self, severity: str = "medium", source: str = "unknown"):
        """Record a defect that escaped to production."""
        self._defect_escapes.append({
            "timestamp": time.time(),
            "severity": severity,
            "source": source,
        })

    def record_vulnerability_scan(self, vulnerabilities_found: int, total_loc: int):
        """Record a security scan result."""
        self._vulnerabilities = vulnerabilities_found
        self._total_loc = total_loc

    def record_ticket(self, ticket_id: str, resolution_time_hours: float, cost: float = 0.0):
        """Record a support ticket resolution."""
        self._tickets.append({
            "id": ticket_id,
            "timestamp": time.time(),
            "resolution_time": resolution_time_hours,
            "cost": cost,
        })

    def get_pipeline_snapshot(self, window_hours: int = 168) -> PipelineMetrics:
        """Get a snapshot of key pipeline metrics for the specified time window.

        Args:
            window_hours: Time window in hours (default 168 = 7 days)

        Returns:
            PipelineMetrics with current values
        """
        now = time.time()
        cutoff = now - window_hours * 3600

        # Filter recent reviews
        recent_reviews = [r for r in self._reviews if r["timestamp"] > cutoff]
        recent_defects = [d for d in self._defect_escapes if d["timestamp"] > cutoff]
        recent_tickets = [t for t in self._tickets if t["timestamp"] > cutoff]

        # Time metrics
        all_times = sorted(self._pr_merge_times)
        recent_times = [r["merge_time"] for r in recent_reviews]

        snapshot = PipelineMetrics()

        if recent_times:
            n = len(recent_times)
            snapshot.mean_merge_time = round(sum(recent_times) / n, 2)
            snapshot.median_merge_time = round(recent_times[n // 2], 2)
            snapshot.p95_merge_time = round(recent_times[int(n * 0.95)] if n > 20 else max(recent_times), 2)

        # Quality metrics
        total_prs = max(len(recent_reviews), 1)
        snapshot.ai_code_ratio = round(self._ai_lines / max(self._total_lines, 1), 2)
        snapshot.escaped_defect_rate = round(len(recent_defects) / max(total_prs, 1), 2)
        snapshot.vulnerability_density = round(
            (self._vulnerabilities / max(self._total_loc, 1)) * 1000, 2
        )

        # Review burden
        total_review_hours = sum(r.get("review_time", 0.5) for r in recent_reviews)
        snapshot.review_burden_hours = round(total_review_hours, 1)
        snapshot.avg_review_time_hours = round(total_review_hours / max(len(recent_reviews), 1), 2)

        # Throughput
        snapshot.prs_merged = len(recent_reviews)
        snapshot.total_lines_changed = sum(r.get("lines", 0) for r in recent_reviews)
        snapshot.ai_generated_lines = int(snapshot.total_lines_changed * snapshot.ai_code_ratio)

        # Cost
        total_cost = sum(t.get("cost", 0) for t in recent_tickets)
        snapshot.cost_per_solved_ticket = round(total_cost / max(len(recent_tickets), 1), 2)
        # Estimate token cost ($0.002 per 1K tokens for review)
        snapshot.estimated_token_cost = round(snapshot.total_lines_changed * 0.0002, 2)

        # Backlog
        snapshot.review_backlog = max(0, self._pr_count - len(recent_reviews))

        # Trend
        if len(self._snapshots) >= 2:
            prev = self._snapshots[-2][1]
            snapshot.week_over_week_change = round(
                ((snapshot.mean_merge_time - prev.mean_merge_time) / max(prev.mean_merge_time, 0.01)) * 100, 1
            )
            if snapshot.week_over_week_change < -10:
                snapshot.trend_direction = "improving"
            elif snapshot.week_over_week_change > 10:
                snapshot.trend_direction = "declining"
            else:
                snapshot.trend_direction = "stable"

        # Store snapshot for trend analysis
        self._snapshots.append((now, snapshot))
        if len(self._snapshots) > 52:  # Keep last year of weekly snapshots
            self._snapshots = self._snapshots[-52:]

        self._save_state()
        return snapshot

    def get_trends(self) -> list[TrendReport]:
        """Get trend analysis comparing current vs previous period."""
        current = self.get_pipeline_snapshot(window_hours=168)
        previous = self.get_pipeline_snapshot(window_hours=336) if len(self._snapshots) >= 2 else None

        if not previous:
            return []

        trends = []

        def calc_trend(name, curr, prev, inverse=False):
            if prev == 0:
                prev = 0.01
            change = ((curr - prev) / prev) * 100
            if inverse:
                is_better = change < -5
                is_worse = change > 5
            else:
                is_better = change < -5
                is_worse = change > 5

            trend = "stable"
            if is_better and not inverse:
                trend = "improving"
            elif is_worse and not inverse:
                trend = "declining"
            elif is_better and inverse:
                trend = "improving"
            elif is_worse and inverse:
                trend = "declining"

            return TrendReport(
                metric_name=name,
                current_value=round(curr, 2),
                previous_value=round(prev, 2),
                change_pct=round(change, 1),
                trend=trend,
                alert=change > 50 or change < -50,
            )

        trends.append(calc_trend("MMT", current.mean_merge_time, previous.mean_merge_time, inverse=True))
        trends.append(calc_trend("EDR", current.escaped_defect_rate, previous.escaped_defect_rate, inverse=True))
        trends.append(calc_trend("Review Burden", current.review_burden_hours, previous.review_burden_hours, inverse=True))
        trends.append(calc_trend("AI Code Ratio", current.ai_code_ratio, previous.ai_code_ratio))
        trends.append(calc_trend("CpST", current.cost_per_solved_ticket, previous.cost_per_solved_ticket, inverse=True))

        return trends

    def export_dashboard(self, output_path: Optional[str] = None) -> dict:
        """Export all metrics as a dashboard-ready JSON payload."""
        snapshot = self.get_pipeline_snapshot()
        trends = self.get_trends()

        dashboard = {
            "generated_at": datetime.now().isoformat(),
            "pipeline_metrics": {
                "mean_merge_time_hours": snapshot.mean_merge_time,
                "median_merge_time_hours": snapshot.median_merge_time,
                "p95_merge_time_hours": snapshot.p95_merge_time,
                "escaped_defect_rate": snapshot.escaped_defect_rate,
                "ai_code_ratio": snapshot.ai_code_ratio,
                "vulnerability_density_per_1k_loc": snapshot.vulnerability_density,
                "review_burden_hours_per_week": snapshot.review_burden_hours,
                "prs_merged": snapshot.prs_merged,
                "review_backlog": snapshot.review_backlog,
                "cost_per_solved_ticket_usd": snapshot.cost_per_solved_ticket,
                "estimated_token_cost_usd": snapshot.estimated_token_cost,
                "trend_direction": snapshot.trend_direction,
            },
            "trends": [
                {
                    "metric": t.metric_name,
                    "current": t.current_value,
                    "previous": t.previous_value,
                    "change_pct": t.change_pct,
                    "trend": t.trend,
                    "alert": t.alert,
                }
                for t in trends
            ],
            "summary": self._generate_summary(snapshot, trends),
        }

        if output_path:
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(dashboard, f, indent=2, ensure_ascii=False)

        return dashboard

    def _generate_summary(self, snapshot: PipelineMetrics, trends: list[TrendReport]) -> str:
        """Generate a human-readable summary of pipeline health."""
        alerts = [t for t in trends if t.alert]
        declining = [t for t in trends if t.trend == "declining"]
        improving = [t for t in trends if t.trend == "improving"]

        lines = [
            f"## Pipeline Health Summary",
            f"",
            f"**Trend**: {snapshot.trend_direction.upper()} | **MMT**: {snapshot.mean_merge_time}h | **EDR**: {snapshot.escaped_defect_rate}",
            f"",
            f"### Key Metrics",
            f"| Metric | Value | Trend |",
            f"|--------|-------|-------|",
        ]
        for t in trends:
            emoji = "🟢" if t.trend == "improving" else "🔴" if t.trend == "declining" else "🟡"
            lines.append(f"| {t.metric_name} | {t.current_value} | {emoji} {t.change_pct:+.1f}% |")

        if alerts:
            lines.append(f"\n### ⚠️ Alerts")
            for t in alerts:
                lines.append(f"- **{t.metric_name}** changed by {t.change_pct:+.1f}%")

        if declining:
            lines.append(f"\n### Recommendations")
            for t in declining:
                if t.metric_name == "MMT":
                    lines.append(f"- Review bottleneck: Consider auto-approving low-risk PRs to reduce MMT")
                elif t.metric_name == "EDR":
                    lines.append(f"- Quality concern: Increase test coverage and add integration tests")
                elif t.metric_name == "Review Burden":
                    lines.append(f"- Team overload: Consider parallel review assignments or AI-assisted review")

        return "\n".join(lines)

    def _save_state(self):
        """Persist metrics state to disk."""
        try:
            os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)
            state = {
                "pr_merge_times": self._pr_merge_times[-1000:],
                "defect_escapes": self._defect_escapes[-1000:],
                "reviews": self._reviews[-5000:],
                "tickets": self._tickets[-5000:],
                "pr_count": self._pr_count,
                "ai_lines": self._ai_lines,
                "total_lines": self._total_lines,
                "vulnerabilities": self._vulnerabilities,
                "total_loc": self._total_loc,
            }
            with open(self.storage_path, "w", encoding="utf-8") as f:
                json.dump(state, f)
        except Exception:
            pass

    def _load_state(self):
        """Load persisted metrics state."""
        try:
            if os.path.exists(self.storage_path):
                with open(self.storage_path, "r", encoding="utf-8") as f:
                    state = json.load(f)
                self._pr_merge_times = state.get("pr_merge_times", [])
                self._defect_escapes = state.get("defect_escapes", [])
                self._reviews = state.get("reviews", [])
                self._tickets = state.get("tickets", [])
                self._pr_count = state.get("pr_count", 0)
                self._ai_lines = state.get("ai_lines", 0)
                self._total_lines = state.get("total_lines", 0)
                self._vulnerabilities = state.get("vulnerabilities", 0)
                self._total_loc = state.get("total_loc", 0)
        except Exception:
            pass

    def reset(self):
        """Reset all metrics to zero."""
        self._pr_merge_times = []
        self._defect_escapes = []
        self._reviews = []
        self._tickets = []
        self._pr_count = 0
        self._ai_lines = 0
        self._total_lines = 0
        self._vulnerabilities = 0
        self._total_loc = 0
        self._snapshots = []
        self._save_state()
